apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-demo-deployment
  name: nginx-demo-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-demo-deployment
  template:
    metadata:
      labels:
        app: nginx-demo-deployment
    spec:
      containers:
      - image: nginx:1.21.4
        name: nginx
        ports:
        - containerPort: 80
