apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-demo-deployment
  name: nginx-demo-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-demo-deployment
